version: '3.9'
services:

  temirlan_chat_spring:
    build:
      context: .
    image: temirlan_chat_spring
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/course

  postgres:
    image: postgres
    ports:
      - "1111:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: course
      POSTGRES_USER: postgres
